package examenjimmy;

import java.math.BigInteger;
import java.util.ArrayList;

/**
 *
 * @author porfi
 */
public class GUIServidor extends javax.swing.JFrame {

    /**
     * Creates new form GUIServidor
     */
    public GUIServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFTamano_numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFQ = new javax.swing.JTextField();
        JTFP = new javax.swing.JTextField();
        JTFN = new javax.swing.JTextField();
        JTFPhi_n = new javax.swing.JTextField();
        JTFD = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAMensaje = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        JBDecifrar = new javax.swing.JButton();
        JBCifrar = new javax.swing.JButton();
        JBObtener = new javax.swing.JButton();
        guardarRSA = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JTFE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emisortxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tamaño del Número");

        JTFTamano_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTamano_numeroActionPerformed(evt);
            }
        });

        jLabel2.setText("Número q");

        jLabel3.setText("Número p");

        jLabel4.setText("Número n");

        jLabel5.setText("Número d");

        jLabel6.setText("Número phi(n)");

        JTFQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFQActionPerformed(evt);
            }
        });

        JTFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDActionPerformed(evt);
            }
        });

        JTAMensaje.setColumns(20);
        JTAMensaje.setRows(5);
        jScrollPane1.setViewportView(JTAMensaje);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBDecifrar.setText("Descifrar");
        JBDecifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDecifrarActionPerformed(evt);
            }
        });

        JBCifrar.setText("Cifrar");
        JBCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCifrarActionPerformed(evt);
            }
        });

        JBObtener.setText("Obtener RSA");
        JBObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBObtenerActionPerformed(evt);
            }
        });

        guardarRSA.setText("Guardar RSA");
        guardarRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarRSAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarRSA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBObtener)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBCifrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBDecifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(JBDecifrar)
                    .addComponent(JBCifrar)
                    .addComponent(guardarRSA)
                    .addComponent(JBObtener))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setText("Número e");

        JTFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEActionPerformed(evt);
            }
        });

        jLabel8.setText("Emisor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFP, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(JTFN, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(JTFPhi_n, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(JTFD, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(JTFE, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(emisortxt)
                            .addComponent(JTFTamano_numero)
                            .addComponent(JTFQ)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emisortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFTamano_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFPhi_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFTamano_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTamano_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTamano_numeroActionPerformed

    private void JTFQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFQActionPerformed

    private void JTFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDActionPerformed
ListaDatos ld = new ListaDatos();
ArrayList<Datitos> ListaDatitos;
Archivo objArchivo = new Archivo();
    private void JBDecifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDecifrarActionPerformed
        //Aqui pa que muestre el mensaje descifrado en el text area del mensaje xD, pero no se como ponerlo x2
        //Aqui tiene que mostar el mensaje
        ld.getDescifrado();
        
        ListaDatitos = objArchivo.leerCif(); 
        JTAMensaje.setText(String.valueOf(ListaDatitos.get(0).getMsjCifrado()));
    }//GEN-LAST:event_JBDecifrarActionPerformed

Rsa rsa = new Rsa();
BigInteger n,q,p, totien,e,d;
BigInteger[] msjCifrado;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int tamanoPrimo = Integer.parseInt(JTFTamano_numero.getText());
        this.JTFE.setText("0");
        this.JTFD.setText("0");
        this.JTFN.setText("0");
        this.JTFP.setText("0");
        this.JTFPhi_n.setText("0");
        this.JTFQ.setText("0");
        this.JTAMensaje.setText("");
        Datos data = new Datos(tamanoPrimo,JTFP,JTFQ,JTFN,JTFPhi_n,JTFD,JTFE,JTAMensaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEActionPerformed

    private void JBCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCifrarActionPerformed
        //En este pues ya va aescribir el mensaje para cifrarlo, se genera un Cifrado.txt para enviar
        n = new BigInteger(JTFN.getText());
        q = new BigInteger(JTFQ.getText());
        p = new BigInteger(JTFP.getText());
        totien = new BigInteger(JTFPhi_n.getText());
        e = new BigInteger(JTFE.getText());
        d = new BigInteger(JTFD.getText());
        System.out.println("n: "+n);
        System.out.println("q: "+q);
        msjCifrado = rsa.encriptar(JTAMensaje.getText(),e,n);
        ld.addCifrado(Integer.parseInt(JTFTamano_numero.getText()), n, q, p, totien, e, d, emisortxt.getText(), Integer.parseInt(JTAMensaje.getText()), msjCifrado);
        ld.grabarCifrado();
    }//GEN-LAST:event_JBCifrarActionPerformed

    private void JBObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBObtenerActionPerformed
        //Aqui para cuando usemos pull para cifrar
        ld.getDatosArch();
        //Aqui no se como poner lo de los sout en los campos, puedes veeer? pofavo uwu
        //Osea nomas que ponga los datos en los campos uwu
    }//GEN-LAST:event_JBObtenerActionPerformed

    private void guardarRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarRSAActionPerformed
        //Este crea el RSA que al hacer uno push, el otro hace pull para cifrar el mensaje uwu
        n = new BigInteger(JTFN.getText());
        q = new BigInteger(JTFQ.getText());
        p = new BigInteger(JTFP.getText());
        totien = new BigInteger(JTFPhi_n.getText());
        e = new BigInteger(JTFE.getText());
        d = new BigInteger(JTFD.getText());
        System.out.println("n: "+n);
        System.out.println("q: "+n);
        
        ld.addRSA(Integer.parseInt(JTFTamano_numero.getText()), n, q, p, totien, e, d, emisortxt.getText());
        ld.grabarRSA();
    }//GEN-LAST:event_guardarRSAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCifrar;
    private javax.swing.JButton JBDecifrar;
    private javax.swing.JButton JBObtener;
    private javax.swing.JTextArea JTAMensaje;
    private javax.swing.JTextField JTFD;
    private javax.swing.JTextField JTFE;
    private javax.swing.JTextField JTFN;
    private javax.swing.JTextField JTFP;
    private javax.swing.JTextField JTFPhi_n;
    private javax.swing.JTextField JTFQ;
    private javax.swing.JTextField JTFTamano_numero;
    private javax.swing.JTextField emisortxt;
    private javax.swing.JButton guardarRSA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
